import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Input, Button, Panel, InputGroup } from 'rsuite'
import VisibleIcon from '@rsuite/icons/Visible'
import UnvisibleIcon from '@rsuite/icons/Unvisible'
import { useEffect, useState } from 'react'
import 'firebase/database'
import Auth from '../components/auth/FireBaseAuth'
import MainView from './mainView'

function check(login, pass) {
  if (!login || !pass) return false

  return true
}

const Home = () => {
  const [login, setLogin] = useState('')
  const [pass, setPass] = useState('')
  const [authenticated, setAuthenticated] = useState(false)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    if (authenticated) {
      const unloadCallback = (event) => {
        event.preventDefault()
        event.returnValue = ''
        return ''
      }
      window.addEventListener('beforeunload', unloadCallback)
      return () => window.removeEventListener('beforeunload', unloadCallback)
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Aplikacja Dzienniczek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Aplikacja Dzienniczek - Administrator</h1>
        {!authenticated && (
          <Panel
            shaded
            bordered
            style={{
              display: 'flex',
              flexDirection: 'column',
              marginTop: 50,
              width: 400,
              gap: 10
            }}
            header="Logowanie:"
          >
            <label style={{ marginLeft: 5, fontSize: '90%' }}>Login:</label>
            <Input
              style={{ marginBottom: 15 }}
              value={login}
              placeholder="Pesel..."
              onChange={(value) => {
                setLogin(value)
              }}
            />
            <label style={{ marginLeft: 5, fontSize: '90%' }}>Hasło:</label>
            <InputGroup inside style={styles}>
              <Input
                type={visible ? 'text' : 'password'}
                value={pass}
                placeholder="Hasło..."
                onChange={(value) => {
                  setPass(value)
                }}
              />
              <InputGroup.Button onClick={() => setVisible(!visible)}>
                {visible ? (
                  <VisibleIcon style={{ fontSize: '1.5em' }} />
                ) : (
                  <UnvisibleIcon style={{ fontSize: '1.5em' }} />
                )}
              </InputGroup.Button>
            </InputGroup>
            <div
              style={{
                display: 'flex',
                marginTop: 50,
                justifyContent: 'center',
                gap: 10
              }}
            >
              <Button
                color="green"
                appearance="primary"
                onClick={() => {
                  if (check(login, pass)) {
                    Auth(login, pass, setAuthenticated)
                  }
                }}
              >
                Zaloguj
              </Button>
            </div>
          </Panel>
        )}
        {authenticated && <MainView authenticated={authenticated} />}
      </main>
    </div>
  )
}

export default Home
